#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "-Tf" ]; then
  shift
  destino="${@: -1}"
  if [ -L "$destino" ] || [ -f "$destino" ]; then
    /bin/rm "$destino"
  fi
  /bin/mv -f "$@"
else
  /bin/mv "$@"
fi
